[workspace]
members = ["test_utils"]
exclude = ["fuzz"]
resolver = "2"

[package]
name = "geogram_predicates"
description = "Dependency-free Rust port of Geogram's robust predicates (PCK)"
version = "0.4.0"
edition = "2021"
rust-version = "1.70"

repository = "https://github.com/glennDittmann/geogram_predicates"
authors = ["Glenn Dittmann", "TimTheBig"]
license = "LGPL-3.0 OR MIT"
include = ["src/**/*.rs", "examples/**/*.rs", "README.md", "Cargo.toml"]

keywords = ["computer-graphics", "math", "geometry", "predicates", "robust"]
categories = ["mathematics", "graphics"]

[dependencies]

[dev-dependencies]
test_utils = { path = "test_utils" }

[package.metadata.docs.rs]
all-features = true
